//! A real, read-only file system: the tree under `./fs` in this crate,
//! walked once by `build.rs` and baked into the compiled binary. Every
//! file's bytes come from `include_bytes!`, so browsing it needs nothing
//! beyond the wasm binary itself — no backend, no runtime fetches to list
//! a directory or read a file. Walking a path into the tree (`resolve`) is
//! pure logic over already-fetched data, not kernel state, so that lives
//! in `app::file_explorer` instead.
//!
//! `build.rs` requires every file and folder under `fs/` to carry a
//! sibling `<name>.meta` file (`created:`/`modified:` fields) — the build
//! fails with a clear message if one is missing.

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum FileKind {
    Text,
    Image,
    Audio,
    Code,
    Config,
    Binary,
    /// A launchable program. This module doesn't know what running one
    /// means — it's just a file kind with its own icon — the File
    /// Explorer app is the one that wires clicking it to actually
    /// launching something.
    Executable,
}

impl FileKind {
    pub fn icon(&self) -> &'static str {
        match self {
            FileKind::Text => "\u{1F4C4}",
            FileKind::Image => "\u{1F5BC}\u{FE0F}",
            FileKind::Audio => "\u{1F3B5}",
            FileKind::Code => "\u{1F9E9}",
            FileKind::Config => "\u{2699}\u{FE0F}",
            FileKind::Binary => "\u{1F4E6}",
            FileKind::Executable => "\u{1F680}",
        }
    }
}

/// When a file or folder was created / last modified. Read from its
/// sidecar `.meta` file at compile time; synthetic entries (the
/// "Applications" folder and its executables) have none.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct EntryMeta {
    pub created: &'static str,
    pub modified: &'static str,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct FileNode {
    pub name: &'static str,
    pub kind: FileKind,
    pub meta: Option<EntryMeta>,
    pub content: &'static [u8],
}

#[derive(Clone, Debug, PartialEq)]
pub struct DirNode {
    pub name: &'static str,
    pub meta: Option<EntryMeta>,
    pub dirs: Vec<DirNode>,
    pub files: Vec<FileNode>,
}

impl DirNode {
    pub fn entry_count(&self) -> usize {
        self.dirs.len() + self.files.len()
    }
}

fn file(name: &'static str, kind: FileKind, meta: Option<EntryMeta>, content: &'static [u8]) -> FileNode {
    FileNode { name, kind, meta, content }
}

fn dir(name: &'static str, meta: Option<EntryMeta>, dirs: Vec<DirNode>, files: Vec<FileNode>) -> DirNode {
    DirNode { name, meta, dirs, files }
}

// Generated by build.rs: `fn build_tree() -> DirNode`, one `dir(...)` /
// `file(...)` call per entry under `./fs`, real content via
// `include_bytes!`.
include!(concat!(env!("OUT_DIR"), "/fs_data.rs"));

/// Builds a fresh copy of the real file tree rooted at `./fs`.
pub(super) fn root() -> DirNode {
    build_tree()
}
